### ISSUE TITLE
Rocoto shows a task status as "UNAVAILABLE" when the job is running

### ISSUE THREAD

**Issue by natalie-perlin** [christopherwharrop/rocoto#96]
Using rocoto tag 1.3.3 or 1.3.5 (same behavior) for UFS-SRW workflow runs on Gaea system. 
Job status never shows up as "RUNNING", it only shows as "UNAVAILABLE" when the job is actually running. When the batch job completes, and the rocotorun/rocotostat sequences are run, the job is shown as "SUCCEEDED".

Example:
```
(workflow_tools) [role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16]# rocotorun -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
(workflow_tools) [role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16]# rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202105121200               make_grid                   269298143           SUCCEEDED                   0         1          28.0
202105121200               make_orog                   269298157           SUCCEEDED                   0         1          66.0
202105121200          make_sfc_climo                   269298163           SUCCEEDED                   0         1          61.0
202105121200           get_extrn_ics                   206556169           SUCCEEDED                   0         1          22.0
202105121200          get_extrn_lbcs                   206556179           SUCCEEDED                   0         1          23.0
202105121200         make_ics_mem001                   269298243           SUCCEEDED                   0         1          41.0
202105121200        make_lbcs_mem001                   269298244           SUCCEEDED                   0         1          44.0
202105121200         run_fcst_mem001                   269298248            UNAVAILABLE                 -         0           0.0
202105121200         make_ics_mem002                   269298245           SUCCEEDED                   0         1          38.0
202105121200        make_lbcs_mem002                   269298246           SUCCEEDED                   0         1          37.0
202105121200         run_fcst_mem002                   269298249         UNAVAILABLE                   -         0           0.0
202105121200    run_post_mem001_f000                   269298251         UNAVAILABLE                   -         0           0.0
...

(workflow_tools) role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16]# squeue -u role.epic
JOBID       CLUSTER  PARTITION  QOS         USER                STATE    TIME_LEFT   NODES  NAME                
269298249   c4       batch      windfall    role.epic           RUNNING  51:53       1      run_fcst_mem002     
269298248   c4       batch      windfall    role.epic           RUNNING  51:50       1      run_fcst_mem001     
```

**Comment by SamuelTrahanNOAA** [comment]
Do you see any messages about those jobs in Rocoto's log file?

Also, what is the output of this command?

```
squeue -u $USER --federation -t all -O jobid:40,username:40,numcpus:10,partition:20,submittime:30,starttime:30,endtime:30,priority:30,exit_code:10,state:30,name:200
```

**Comment by natalie-perlin** [comment]
@SamuelTrahanNOAA - thanks for the comment on the issue!

A currently running example:
```
# squeue -u $USER --federation -t all -O jobid:40,username:40,numcpus:10,partition:20,submittime:30,starttime:30,endtime:30,priority:30,exit_code:10,state:30,name:200
JOBID                                   USER                                    CPUS      PARTITION           SUBMIT_TIME                   START_TIME                    END_TIME                      PRIORITY                      EXIT_CODE STATE                         NAME                                                                                                                                                                                                    
206556406                               role.epic                               36        batch               2023-07-10T21:51:43           2023-07-10T21:51:43           2023-07-10T21:53:02           0.00000000023283              0:0       COMPLETED                     make_orog                                                                                                                                                                                               
206556404                               role.epic                               36        batch               2023-07-10T21:50:46           2023-07-10T21:50:47           2023-07-10T21:51:13           0.00000000023283              0:0       COMPLETED                     get_extrn_lbcs                                                                                                                                                                                          
206556402                               role.epic                               32        batch               2023-07-10T21:50:45           2023-07-10T21:50:45           2023-07-10T21:52:44           0.00000000023283              0:0       COMPLETED                     get_extrn_ics                                                                                                                                                                                           
206556400                               role.epic                               36        batch               2023-07-10T21:50:44           2023-07-10T21:50:44           2023-07-10T21:51:18           0.00000000023283              0:0       COMPLETED                     make_grid                                                                                                                                                                                               
206556409                               role.epic                               72        batch               2023-07-10T21:53:18           2023-07-10T21:53:19           2023-07-10T22:13:19           0.00000000023283              0:0       RUNNING                       make_sfc_climo                                                                                                                                                                                          

```

```
# rocotorun -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
# rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
201907010000               make_grid                   206556400         UNAVAILABLE                   -         0           0.0
201907010000               make_orog                   206556406         UNAVAILABLE                   -         0           0.0
201907010000          make_sfc_climo                   206556409         UNAVAILABLE                   -         0           0.0
201907010000           get_extrn_ics                   206556402         UNAVAILABLE                   -         0           0.0
201907010000          get_extrn_lbcs                   206556404         UNAVAILABLE                   -         0           0.0
201907010000         make_ics_mem000                           -                   -                   -         -             -
201907010000        make_lbcs_mem000                           -                   -                   -         -             -
201907010000         run_fcst_mem000                           -                   -                   -         -             -
201907010000    run_post_mem000_f000                           -                   -                   -         -             -
201907010000    run_post_mem000_f001                           -                   -                   -         -             -
201907010000    run_post_mem000_f002                           -                   -                   -         -             -
201907010000    run_post_mem000_f003                           -                   -                   -         -             -
201907010000    run_post_mem000_f004                           -                   -                   -         -             -
201907010000    run_post_mem000_f005                           -                   -                   -         -             -
201907010000    run_post_mem000_f006     
```

**Comment by natalie-perlin** [comment]
This time, even when the tasks succeeded, their status showed as "UNAVAILABLE"

**Comment by natalie-perlin** [comment]
The task 206556409 completed:
```
squeue -u $USER --federation -t all -O jobid:40,username:40,numcpus:10,partition:20,submittime:30,starttime:30,endtime:30,priority:30,exit_code:10,state:30,name:200
JOBID                                   USER                                    CPUS      PARTITION           SUBMIT_TIME                   START_TIME                    END_TIME                      PRIORITY                      EXIT_CODE STATE                         NAME                                                                                                                                                                                                    
206556409                               role.epic                               72        batch               2023-07-10T21:53:18           2023-07-10T21:53:19           2023-07-10T21:54:39           0.00000000023283              0:0       COMPLETED                     make_sfc_climo                                                                                                                                                                                          

```

**Comment by natalie-perlin** [comment]
After some time, the status of completed jobs turns to "SUCCEEDED", and subsequent running jobs show as "UNAVAILABLE".

```
rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
201907010000               make_grid                   206556400           SUCCEEDED                   0         1          34.0
201907010000               make_orog                   206556406           SUCCEEDED                   0         1          79.0
201907010000          make_sfc_climo                   206556409           SUCCEEDED                   0         1          80.0
201907010000           get_extrn_ics                   206556402           SUCCEEDED                   0         1         119.0
201907010000          get_extrn_lbcs                   206556404           SUCCEEDED                   0         1          26.0
201907010000         make_ics_mem000                   206556412         UNAVAILABLE                   -         0           0.0
201907010000        make_lbcs_mem000                   206556414         UNAVAILABLE                   -         0           0.0
201907010000         run_fcst_mem000                           -                   -                   -         -             -
201907010000    run_post_mem000_f000                           -                   -                   -         -             -
201907010000    run_post_mem000_f001                           -                   -                   -         -             -

...
```

**Comment by SamuelTrahanNOAA** [comment]
@natalie-perlin I think I found the error. It is a typo in the squeue parser in slurmbatchsystem.rb:

```ruby
  code_signal=job[230..239].strip
  if code_signal=~ /:/
  
    code,signal=core_signal.split(":").collect {|i| i.to_i}
```

The last line has `core_signal`, but the variable name is `code_signal`. When ruby sees that, it raises an exception.

```
./test.rb:17:in `block in <main>': undefined method `strip' for nil:NilClass (NoMethodError)
        from ./test.rb:4:in `each'
        from ./test.rb:4:in `<main>'
```
The exception refers to the wrong line and doesn't specify the variable. (Line 17 is blank.) However, in my little ruby test program, if I fix the typo, parsing works.

**Comment by christopherwharrop-noaa** [comment]
@SamuelTrahanNOAA - Thank you for finding that!  I'm very surprised this has existed for so long and was only discovered when running on Gaea.  I wonder if other machines aren't outputting a status with a colon in it?  Either way, this is a very simple fix which can be submitted and merged right away.

**Comment by SamuelTrahanNOAA** [comment]
I'm compiling on GAEA a Rocoto with the fix. I'll give it to @natalie-perlin to test, once it has compiled.

**Comment by christopherwharrop-noaa** [comment]
@SamuelTrahanNOAA - Thank you.  If that test passes, and you have a PR ready to go, I'll get it reviewed right away.

**Comment by SamuelTrahanNOAA** [comment]
@natalie-perlin - Please test this version of Rocoto and see if it fixes the problem.

```
module use /lustre/f2/dev/Samuel.Trahan/rocoto/modulefiles
module load rocoto/code-not-core
```

**Comment by natalie-perlin** [comment]
@SamuelTrahanNOAA - tried to use your module, and it appears to be permission issue (reading):
```
[role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/srw-dev-upd/modulefiles]# module use /lustre/f2/dev/Samuel.Trahan/rocoto/modulefiles
[role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/srw-dev-upd/modulefiles]# module avail rocoto
No module(s) or extension(s) found!
If the avail list is too long consider trying:

"module --default avail" or "ml -d av" to just list the default modules.
"module overview" or "ml ov" to display the number of modules for each name.

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".


[role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/srw-dev-upd/modulefiles]# cd /lustre/f2/dev/Samuel.Trahan/rocoto/modulefiles
bash: cd: /lustre/f2/dev/Samuel.Trahan/rocoto/modulefiles: Permission denied
```

**Comment by SamuelTrahanNOAA** [comment]
Yes, yes, accessing the files. Important detail, that. A moment ago, I chmodded them so you can access them. Please try again.

**Comment by natalie-perlin** [comment]
Still got permission issues; they may need to be set for parent directories for the access (m.b. using setfacl).
However, I've successfully used code built from your repository as in https://github.com/christopherwharrop/rocoto/pull/97.  Re-ran a couple of the last tasks after rewinding them. The status of the running jobs is shown as "RUNNING"
All looks good now!  :) 

```
suite_GFS_v16]# rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10 
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
201907010000               make_grid                   206556400           SUCCEEDED                   0         1          34.0
201907010000               make_orog                   206556406           SUCCEEDED                   0         1          79.0
201907010000          make_sfc_climo                   206556409           SUCCEEDED                   0         1          80.0
201907010000           get_extrn_ics                   206556402           SUCCEEDED                   0         1         119.0
201907010000          get_extrn_lbcs                   206556404           SUCCEEDED                   0         1          26.0
201907010000         make_ics_mem000                   206556412           SUCCEEDED                   0         1         143.0
201907010000        make_lbcs_mem000                   206556414           SUCCEEDED                   0         1         215.0
201907010000         run_fcst_mem000                   206556419           SUCCEEDED                   0         1         582.0
201907010000    run_post_mem000_f000                   206556425           SUCCEEDED                   0         1         134.0
201907010000    run_post_mem000_f001                   206556427           SUCCEEDED                   0         1         125.0
201907010000    run_post_mem000_f002                   206556429           SUCCEEDED                   0         1         122.0
201907010000    run_post_mem000_f003                   206556433           SUCCEEDED                   0         1         125.0
201907010000    run_post_mem000_f004                   206556435           SUCCEEDED                   0         1          30.0
201907010000    run_post_mem000_f005                   206557611           SUCCEEDED                   0         1         126.0
201907010000    run_post_mem000_f006                   206557618             RUNNING                   -         0           0.0
(workflow_tools) [role.epic@Gaea:/lustre/f2/dev/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16]# 

```
